### ISSUE TITLE
fullDiv in FullMath Library does not work correctly

### ISSUE THREAD

**Issue by yonggewang** [Uniswap/uniswap-lib#24]
This function does not work correctly. If you call: fullDiv(
        uint256 l,
        uint256 h,
        uint256 d
    ) 

with l=238, d = 234, the return value is: 72246346276274207401031469278924933959732554534972317734020543868185115074491

if you call with l=2m d=234, the output is:
94019217756795201412301227143806420906501269600306440886739063938049122357213

**Comment by moodysalem** [comment]
in your examples what is h?

**Comment by yonggewang** [comment]
h = 0

try many other cases by setting h =0.. I am not sure whether h=1 will give problems since the number is too larger to check manually. But set h=0, and try different l and d.. e.g., l=29 and d=30 (h=0).. you will see the crazy results

**Comment by moodysalem** [comment]
i can't seem to find a case where this breaks mulDiv which is the only function exposed by FullMath, ~but i don't think `l` of 238 and `h` of 0 represents the integer 238 so it's not obvious what the answer is supposed to be~

~e.g. if you run fullMul(238, 1) you should get ~
```
        uint256 mm = mulmod(x, y, uint256(-1)); // 238
        l = x * y; // 238
        h = mm - l; // 238-238 == 0
        if (mm < l) h -= 1; // true, h == uint256(-1)
```

I think if you run `fullDiv` with l=238 and `h=uint256(-1)` and `d=234` you should get 1

**Comment by yonggewang** [comment]
I am not sure whether it will introduce problems for fullDiv.
I am concerned with the fullDiv itself. It looks to me like an implementation of Newton's method. But in the iteration
r *= 2 - d * r;, both d and r are 256-bits. So d * r overflows and one only gets the least significant 256 bits. I think in Newton's method, one cannot ignore these truncated bits...

if fullDiv does not work for the simple case of h=0 (I am not sure whether it will work correctly for h>0), one may have concerns for the general case.

**Comment by yonggewang** [comment]
OK. I think I understand what is the function is for... fullDiv is not an actual division function. It is only a help function with (h,l) a multiple of d... For that purpose, the function works as it is. thanks!
