### ISSUE TITLE
PairNamer.sol requires solidity version <0.7.0

### ISSUE THREAD

**Issue by dgczhh** [Uniswap/uniswap-lib#8]
After version `0.7.0`,while regular string literals can only contain ASCII, Unicode literals – prefixed with the keyword unicode – can contain any valid UTF-8 sequence.

`string memory a = unicode"Hello 😃";`

So the pragma  in PairName.sol should be `solidity >=0.5.0 <0.7.0;`

**Comment by moodysalem** [comment]
Good to know, but, honestly not sure the point of the pragma if it will error for you in exactly the way it's not compatible
